### ISSUE TITLE
Bug - not in transaction

### ISSUE THREAD

**Issue by marekmagik** [marek1840/IOSR2015-facebook-recommendations#19]
Exception in thread "taskExecutor-1" org.neo4j.graphdb.NotInTransactionException
	at org.neo4j.kernel.impl.transaction.AbstractTransactionManager.assertInTransaction(AbstractTransactionManager.java:84)
	at org.neo4j.kernel.impl.core.NodeManager.getNodeByIdOrNull(NodeManager.java:312)
	at org.neo4j.kernel.impl.core.NodeManager.getNodeById(NodeManager.java:320)
	at org.neo4j.kernel.InternalAbstractGraphDatabase.getNodeById(InternalAbstractGraphDatabase.java:1183)
	at org.springframework.data.neo4j.support.DelegatingGraphDatabase.getNodeById(DelegatingGraphDatabase.java:95)
	at org.springframework.data.neo4j.support.mapping.EntityStateHandler.getPersistentState(EntityStateHandler.java:113)
	at org.springframework.data.neo4j.support.mapping.EntityStateHandler.getPersistentState(EntityStateHandler.java:99)
	at org.springframework.data.neo4j.support.mapping.Neo4jEntityPersister.getPersistentState(Neo4jEntityPersister.java:221)
	at org.springframework.data.neo4j.support.Neo4jTemplate.getPersistentState(Neo4jTemplate.java:247)
	at org.springframework.data.neo4j.fieldaccess.RelationshipHelper.getNode(RelationshipHelper.java:208)
	at org.springframework.data.neo4j.fieldaccess.RelationshipHelper.checkAndGetNode(RelationshipHelper.java:75)
	at org.springframework.data.neo4j.fieldaccess.RelatedToViaCollectionFieldAccessorFactory$RelatedToViaCollectionFieldAccessor.setValue(RelatedToViaCollectionFieldAccessorFactory.java:87)
	at org.springframework.data.neo4j.fieldaccess.ManagedFieldAccessorSet.updateValue(ManagedFieldAccessorSet.java:112)
	at org.springframework.data.neo4j.fieldaccess.ManagedFieldAccessorSet.update(ManagedFieldAccessorSet.java:100)
	at org.springframework.data.neo4j.fieldaccess.ManagedFieldAccessorSet.add(ManagedFieldAccessorSet.java:126)
	at pl.recommendations.db.person.PersonNode.addFriend(PersonNode.java:51)
	at pl.recommendations.crawling.embedded.EmbeddedCrawlerEndpoint$$Lambda$57/1202880207.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at pl.recommendations.crawling.embedded.EmbeddedCrawlerEndpoint.onAddFriends(EmbeddedCrawlerEndpoint.java:73)
	at pl.recommendations.crawling.CrawledDataCache.lambda$addFriendAndNotify$8(CrawledDataCache.java:99)
	at pl.recommendations.crawling.CrawledDataCache$$Lambda$55/1792839975.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476)
	at pl.recommendations.crawling.CrawledDataCache.addFriendAndNotify(CrawledDataCache.java:99)
	at pl.recommendations.crawling.CrawledDataCache.lambda$onNewPerson$1(CrawledDataCache.java:46)
	at pl.recommendations.crawling.CrawledDataCache$$Lambda$50/2113386603.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at pl.recommendations.crawling.CrawledDataCache.onNewPerson(CrawledDataCache.java:46)
	at pl.recommendations.crawling.CrawlerScheduler.crawlPersonName(CrawlerScheduler.java:100)
	at pl.recommendations.crawling.CrawlerScheduler.consumeUserTask(CrawlerScheduler.java:128)
	at pl.recommendations.crawling.CrawlerScheduler$$Lambda$9/393098700.apply(Unknown Source)
	at pl.recommendations.crawling.CrawlerScheduler.run(CrawlerScheduler.java:108)
	at pl.recommendations.crawling.CrawlerScheduler.lambda$new$14(CrawlerScheduler.java:41)
	at pl.recommendations.crawling.CrawlerScheduler$$Lambda$3/299289537.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by marekmagik** [comment]
błąd nie leci dla friends ani interests, jedynie dla users w PersonNode: 51

**Comment by marek1840** [comment]
Używać należy metody addFriend z PersonNodeRepository, ta z PersonNode była wywalona, ale pewnie ktos ją przypadkiem przywrócił robiąc revert.

**Comment by marekmagik** [comment]
zmiana metody na inną załatwiła sprawę.

Done.
